apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-01T08:42:31Z"
  generation: 2
  labels:
    app: orders-service
  name: orders-service
  namespace: default
  resourceVersion: "19821"
  selfLink: /apis/apps/v1/namespaces/default/deployments/orders-service
  uid: b9e11355-73f4-11ea-a266-42010a800072
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: orders-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-service
    spec:
      containers:
      - image: yankitchauhan/ordersimage
        imagePullPolicy: Always
        name: ordersimage-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-01T08:42:36Z"
    lastUpdateTime: "2020-04-01T08:42:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-01T08:42:31Z"
    lastUpdateTime: "2020-04-01T08:42:36Z"
    message: ReplicaSet "orders-service-7449c469b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
