apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-01T08:30:04Z"
  generation: 3
  labels:
    app: users-service
  name: users-service
  namespace: default
  resourceVersion: "17295"
  selfLink: /apis/apps/v1/namespaces/default/deployments/users-service
  uid: fc9ffd52-73f2-11ea-a266-42010a800072
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: users-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: users-service
    spec:
      containers:
      - image: yankitchauhan/usersimage
        imagePullPolicy: Always
        name: usersimage-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-01T08:30:04Z"
    lastUpdateTime: "2020-04-01T08:30:09Z"
    message: ReplicaSet "users-service-5855965bdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-01T08:30:52Z"
    lastUpdateTime: "2020-04-01T08:30:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
